export type BlogPost = {
  slug: string;
  title: string;
  tag: string;
  date: string;
  excerpt: string;
  author: string;
  readTime: string;
  content: string[];
};

export const blogPosts: BlogPost[] = [
  {
    slug: "scanner-on-encore",
    title: "Why we rebuilt our scanner on Encore.ts",
    tag: "Engineering",
    date: "12 May 2026",
    excerpt:
      "We moved 14k lines from a FastAPI monolith to typed Encore services in six weeks. The migration plan, the three things that broke in production the night we cut over, and what we'd do exactly the same again.",
    author: "Andrea — Co-founder",
    readTime: "9 min read",
    content: [
      "Six weeks ago, the scanner that powers Dockier was a 14,000-line FastAPI monolith. It worked. It was also the bottleneck on every product decision we made — every new analyser meant another endpoint hand-wired into the same Python process, another set of Pydantic models, another deployment we had to coordinate.",
      "Today it's eight Encore.ts services, each one owned end-to-end by typed contracts that the client also reads. This post is the migration in honest terms — including the night we cut over and broke production for 47 minutes.",
      "## Why we moved",
      "The trigger wasn't language preference. We had a working Python codebase with decent test coverage. Three things stacked up:",
      "- Drift between client and server types. The frontend was TypeScript; the backend was Python. Every API change required two PRs, two schemas, and a handwritten OpenAPI bridge that lied about nullability roughly twice a sprint.",
      "- Deploy coupling. One process meant one deploy. A bug in the dependency scanner blocked shipping a fix to the architecture analyser.",
      "- Per-scan cost. The scanner held memory between requests for warm caches. That's great until you need to scale to 50 concurrent scans and discover you're paying for 50 copies of every parser.",
      "## Why Encore.ts",
      "We looked at Nest, Fastify-with-tRPC, and a hand-rolled Hono setup. Encore won on one boring thing: the type generated for the client is the type the server enforces. There's no intermediate OpenAPI schema, no codegen step, no jsonSchema mismatch. The client imports the server types directly.",
      "That single property removed the most common class of bug we'd been shipping. The second was deployability: every Encore service is its own deploy unit, but local dev runs them as one process. No Docker Compose maze.",
      "## The migration plan",
      "We didn't rewrite. We strangled. The Python monolith ran the same endpoints; a new Cloudflare Worker in front routed slices of traffic to the new Encore services as we brought them up.",
      "- Week 1 — auth + project metadata moved first. Lowest risk, highest leverage.",
      "- Week 2 — dependency scanner. Stateless, easy to A/B against the Python version.",
      "- Weeks 3–4 — the AI analysis pipeline. The hard one. We ran both in parallel for 12 days and compared outputs row-by-row.",
      "- Week 5 — sensitive data scanner. Its schema parsers needed reordering for streaming.",
      "- Week 6 — deploy pipeline + cutover.",
      "## The night of the cutover",
      "We flipped the router at 22:00 UTC. By 22:14 three things were on fire:",
      "- Background jobs lost their context. The Python version pinned a Postgres session per worker. Encore connection-pools per request. A few background jobs depended on the connection being the same one that had set a GUC. We fixed it by passing the GUC explicitly.",
      "- JWT clock skew. The new services validated tokens with a stricter clock-skew tolerance than the legacy ones. Two regions had clocks drifted ~7 seconds. We loosened the leeway to 30s and filed a follow-up to fix NTP.",
      "- Stale env in CDN. The router was reading API base URLs from an env that was injected at edge-build time. We'd updated the source but not re-built. Five-minute fix, embarrassing.",
      "47 minutes later we were green. No data loss. No customer-visible findings lost. The 12-day shadow comparison saved us — we knew the two implementations agreed.",
      "## What we'd do exactly the same",
      "- Shadow both implementations before cutover. Diff their outputs row by row on real workloads. The Python and Encore.ts scanners disagreed on 0.4% of findings; every disagreement was a Python bug we'd been shipping.",
      "- Strangle, don't rewrite. Two-week rewrites become four-month rewrites. Slicing meant we shipped value continuously.",
      "- Use one language end-to-end. The single biggest velocity gain was deleting the OpenAPI bridge. We could have moved Python to TS without Encore — but Encore made the migration cheaper than the alternative.",
      "## What's next",
      "With Encore underneath, the next analyser is a one-day project, not a one-week one. We're adding container-image scanning in June and the SBOM diff view in July. If you want to be in the small early-access cohort that gets those first, the form on the home page works.",
      "> Note on this migration's place in the story: the marketing site you're reading is still in the middle of catching up. The Developer experience section on the home page still references FastAPI — that's the legacy stack and we'll update it as part of the same migration this post describes.",
    ],
  },
  {
    slug: "scanning-ourselves",
    title: "What we found scanning our own codebase on day one",
    tag: "Engineering",
    date: "28 April 2026",
    excerpt:
      "Before we let anyone else point Dockier at their repo, we pointed it at ours. 47 findings, 3 real, 1 embarrassing. The CVEs, the false positives, and the rule we wrote that night.",
    author: "Andrea — Co-founder",
    readTime: "7 min read",
    content: [
      "We shipped a closed beta of Dockier in March. The first thing we did before sending invites was point it at the Dockier monorepo. If a vulnerability scanner can't survive being run on the code that wrote it, the marketing site shouldn't survive either.",
      "Here's what we found on day one — every category, every finding, including the embarrassing one.",
      "## The raw numbers",
      "- 47 findings total across SAST, dependencies, and the schema-aware sensitive-data scanner.",
      "- 3 we agreed were real and needed fixing.",
      "- 1 was the kind of thing you tell people about over beer, not in a postmortem.",
      "- 43 were noise, dupes, or \"yes, and we accept that risk.\"",
      "## The three real ones",
      "### 1. A dangerouslySetInnerHTML call rendering Markdown without sanitisation",
      "Our changelog page rendered post bodies through marked and dropped the result straight into the DOM. The risk was real but bounded — only authors could write changelog entries — and we'd been treating it as a defence-in-depth item we'd \"get to.\" The scanner found it on day one and we shipped DOMPurify the same afternoon.",
      "### 2. A Postgres query concatenated with an untrusted ref string",
      "The branch-comparison endpoint took a Git ref and used it inside a query that also templated table names. We'd pre-validated the ref against a regex but the regex allowed dots. main.commits wasn't a valid ref but we hadn't proven that to ourselves. Fix: parameterised query plus an explicit allowlist of table targets.",
      "### 3. A leaked GCP service-account key in an old commit",
      "Buried in a commit from January. The key had already been rotated, but the commit was still public on a fork. We squashed-and-force-pushed and notified GitHub's secret-scanning team. The scanner flagged the original commit hash which made the cleanup deterministic.",
      "## The embarrassing one",
      "The sensitive-data scanner flagged our own users table for storing plaintext API tokens. They were one-way hashed before storage — but the column was called api_token with no _hash suffix. The scanner couldn't tell. We renamed the column, added a comment to the migration, and wrote a rule that suppresses the finding when the column has a corresponding verify_* function within the same file.",
      "> That last bit is now an open rule in our public rule set. If you also store hashed tokens with naked names, the rule will save you from the same review.",
      "## The 43 we ignored",
      "Worth being honest about: most findings on most repos aren't actionable. Out of the 43 we marked as noise, the largest categories were:",
      "- 14 hits on test fixtures that contained \"dummy\" secrets.",
      "- 9 \"use HTTPS\" findings in markdown files (not code).",
      "- 6 dependency CVEs that didn't reach our use of the library.",
      "- 5 deprecation warnings we'd already triaged.",
      "- The rest were a mix of style preferences and rules we don't agree with.",
      "We've since added a \"scope\" field to every rule that asks whether the finding is on production code paths. That cut the noise in half on the next run.",
      "## What this taught us about the product",
      "Two things, both unsurprising in retrospect:",
      "- Severity isn't the whole story. A \"critical\" SQL-injection finding on a script you run locally once a quarter is less urgent than a \"medium\" XSS on your billing portal. We've added a reachability signal that the rule can opt into.",
      "- The team's first scan determines whether they'll do a second. 47 findings on a 200-file repo would have buried us. The first-scan view now groups by \"real / probably real / context-required\" — and lets you tag everything in the third bucket in one click.",
      "If you want to do this on your own codebase, the early-access form is on the home page. We're prioritising teams who'll send us their day-one screenshot.",
    ],
  },
  {
    slug: "sensitive-data-without-an-llm",
    title: "Detecting sensitive data without an LLM",
    tag: "Security",
    date: "14 April 2026",
    excerpt:
      "A 320-line schema parser beats GPT-4o on PII classification — 12× faster, zero per-scan cost, no hallucinated labels. We still ship the model as a tie-breaker. Here's the breakdown of when each one wins.",
    author: "Dockier Security",
    readTime: "8 min read",
    content: [
      "Most PII-detection demos look like this: paste a schema, watch GPT-4o emit a confident list of columns. It's a great demo and a bad product. Confidence is not accuracy, the model bills per token, and \"the LLM said so\" is the wrong defence to bring to a SOC 2 auditor.",
      "We shipped a 320-line schema parser that beats GPT-4o on the benchmark we care about. We also still ship the LLM. Here's where each one wins.",
      "## What we actually parse",
      "The parser reads schemas — not data — for five sources: raw SQL DDL, Prisma, Eloquent (Laravel), TypeScript-with-decorators (TypeORM / MikroORM), and Python (SQLAlchemy / Pydantic). For each table or model we extract:",
      "- Column name and type.",
      "- Comments and decorator metadata (e.g. @Index, @Encrypted).",
      "- Relations — because users.email being PII propagates a label to signups.email if they're related, even if the second isn't named obviously.",
      "- Any nearby validation rules — Zod schemas, FastAPI models, Laravel form requests.",
      "Classification is then a deterministic decision tree: column name regex, type check, comment override, relation propagation. There is no model.",
      "## The benchmark",
      "We built a benchmark from 12 open-source codebases — Mastodon, PostHog, Discourse, Cal.com, and so on — totalling 3,400 columns. We hand-labelled them across four classes: None, PII, Sensitive, Secret.",
      "- Parser only: 96.2% precision, 91.4% recall.",
      "- GPT-4o only: 88.5% precision, 84.7% recall, $0.07 per repo.",
      "- Parser → LLM tie-breaker: 97.8% precision, 93.1% recall, $0.004 per repo.",
      "The parser wins because PII detection is overwhelmingly a pattern-matching problem with a known small vocabulary. email, phone, ssn, address, dob, passport — the long tail of edge cases is shorter than people think. The model wins on ambiguous columns where the name carries no signal — note_field, meta, payload — and we use it to break ties when the parser's confidence is below a threshold.",
      "## Why the parser was 12× faster",
      "A scan of 3,400 columns runs in ~180ms on a laptop. The same workload through an LLM takes ~2,200ms even with batched prompts, because you're bottlenecked on TTFT. For a scanner that runs on every commit, that's the difference between CI passing in 8 seconds and CI passing in 35 seconds — which is the difference between developers leaving the integration on and turning it off.",
      "## The edge cases that bit us",
      "- Polymorphic columns. Eloquent's morphTo tables have a {name}_id + {name}_type pair. The id isn't PII on its own; with the type column it might be. We had to teach the parser about morph relations.",
      "- JSON blobs. A column called metadata jsonb is a hole the parser can't see into. We added a config knob to mark any JSON column as Sensitive by default with an explicit opt-out.",
      "- Pydantic optional unions. Union[str, None] with a Field description that mentioned \"email\" used to fall through the cracks. Fixed.",
      "## When you should still use the LLM",
      "We still call it in three situations: when the column name is opaque (data, payload), when there's a comment that needs interpreting (\"stores user-supplied feedback\"), and when relations infer labels we want a second opinion on. Each call is a single ~120-token prompt; the bill is closer to free than to expensive.",
      "> If you want to reproduce the benchmark, the labelled dataset lives in the public dockier/pii-benchmark repo. PRs welcome — especially for Ruby/Active Record models, which we under-tested.",
    ],
  },
  {
    slug: "osv-dependency-scanner",
    title: "OSV.dev: the dependency scanner you already have",
    tag: "Security",
    date: "02 April 2026",
    excerpt:
      "Google's open vulnerability database covers more ecosystems than Snyk's free tier, ships under Apache 2.0, and needs no API key. A tour of the OSV ecosystem and the four sharp edges we hit integrating it.",
    author: "Dockier Security",
    readTime: "10 min read",
    content: [
      "Snyk's free tier limits you to 100 tests per month. GitHub Advanced Security is bundled with a $49/user/month seat. Mend's free plan needs a sales call. Meanwhile Google has been quietly running OSV.dev — a free, open, no-API-key vulnerability database that covers more ecosystems than any of them.",
      "This post is a tour of OSV — what it is, where it wins, where it doesn't, and the four sharp edges we hit integrating it.",
      "## What OSV actually is",
      "OSV is two things: a public vulnerability database under Apache 2.0, and a machine-readable schema for vulnerability records. The schema is the important bit. Every record names the affected package, the affected version ranges, and (often) the introducing and fixing commits. No CVSS-by-feel, no marketing summaries — just packages, versions, and references.",
      "The database currently aggregates from PyPI, npm, Cargo, Maven, NuGet, RubyGems, Packagist, Go, Hex, Pub, Swift, Bitnami, OSS-Fuzz, RustSec, GitHub Security Advisories, and a few more. That's broader coverage than Snyk's free tier and much broader than GHAS.",
      "## Three things it does well",
      "- Version-range queries. Send a package name and version, get back the vulnerabilities that affect that exact version. No false positives from version ranges that look unaffected once you read the patch.",
      "- Commit-level queries. If you build from source, you can query by commit hash. Most scanners can't do this.",
      "- No API key. No rate-limit headers, no auth, no quota. (There are courtesy limits but you'd have to be hammering it.)",
      "## The four sharp edges",
      "### 1. Date semantics are inconsistent across ecosystems",
      "OSV records have a published date and a modified date. For PyPI advisories these are the GitHub-advisory dates, not the PyPI-release dates. For RustSec they're the advisory authoring dates. If you display \"this CVE has been known for X days\" you need to normalise. We dropped the date column from our UI until we'd figured out a coherent story.",
      "### 2. Some ecosystems return alias chains",
      "A vulnerability can have a primary OSV ID, a CVE, a GHSA, and an upstream-specific ID. The same vulnerability might appear in your results 2–4 times if you join records naïvely. We deduplicate by walking the aliases array as a graph and keeping the lowest-prefixed canonical ID.",
      "### 3. The \"affected\" field is permissive",
      "Version ranges are expressed as { introduced: 1.0.0, fixed: 2.0.0 } — but ecosystems treat semver differently. Cargo prereleases (2.0.0-rc1) sort before 2.0.0; npm 0.1.0-beta can or can't, depending on the comparator. We ended up writing a per-ecosystem semver matcher and pinning it against the OSV examples corpus.",
      "### 4. There's no severity column",
      "OSV records often include a severity CVSS string, but it's optional and frequently absent for non-CVE-derived advisories. If your UI groups by severity, you need to derive it. We fall back to scoring rules: any vulnerability with a CWE in the \"injection\" family is treated as High; anything marked \"denial of service\" without a CWE is Medium; everything else inherits from the upstream advisory if one exists.",
      "## What OSV doesn't replace",
      "- Reachability analysis. OSV tells you what's vulnerable in your dependency graph; it doesn't tell you whether your code actually calls the affected function. That's a different layer.",
      "- License compliance. Adjacent topic, different database. Don't expect OSV to flag a GPL leak.",
      "- Container scans. OSV covers application dependencies; for OS packages you still want Trivy or Grype layered on top.",
      "## How we wire it into Dockier",
      "We ship OSV.dev as the default dependency scanner on every plan, including Free. We hit the public API directly for small repos; for repos with more than 500 dependencies we use the daily SQLite dump that OSV publishes.",
      "That's it. No API key. No rate-limit handling. Just a public database that Google maintains because everyone benefits.",
      "> If you're starting a security platform from scratch, OSV is your dependency scanner. Buying Snyk in 2026 to do what OSV does for free is a story you'll tell your CFO later.",
    ],
  },
  {
    slug: "ai-fix-pr-wrong-primitive",
    title: "The AI-fix PR is the wrong primitive",
    tag: "Product",
    date: "18 March 2026",
    excerpt:
      "Auto-generated fix PRs demo beautifully and pile up unread in production. After three months of watching them go stale, we replaced them with something more boring — and saw remediation rates triple.",
    author: "Dockier Product",
    readTime: "6 min read",
    content: [
      "Every AI-security demo includes the same scene: an LLM looks at a vulnerability, opens a PR with the fix, the reviewer clicks merge. The pitch lands. Buyers nod. Procurement signs.",
      "We shipped exactly that feature in January. Three months later we ripped most of it out. Here's what happened, and what we shipped instead.",
      "## What we expected",
      "The hypothesis was simple: scanners produce findings, findings need fixes, fixes are PRs. Cutting the manual work from \"review finding → write fix → open PR\" to \"review PR\" should be net positive for every team.",
      "## What actually happened",
      "- PRs piled up unread. Across our 12 design partners, the median time-to-review for an AI-opened PR was 8 days. The median for a human-opened PR in the same repos was 19 hours.",
      "- Context evaporated. By the time someone looked at the PR, the finding it was fixing had been triaged, deprioritised, deduplicated, or superseded. The PR's commit message couldn't possibly know.",
      "- Trust eroded. Half of our partners had at least one PR that fixed a finding by deleting the call site. Technically correct. Brand-eroding. One bad PR like that sets the default for the next ten reviews.",
      "The fundamental issue: a PR is the wrong unit of work for a low-confidence decision. PRs imply commitment. They imply someone read the change, agreed with it, and is asking for it to ship. AI fixes are an opening offer, not a commitment.",
      "## What we shipped instead",
      "The new primitive is what we call a fix draft. It sits inside the finding view, not in the repo. It's a diff. You can read it, edit it inline, ask for an alternative, then click \"Open as PR\" when you actually want it to be a PR.",
      "Three things changed when we moved from PRs to fix drafts:",
      "- Remediation rate tripled. Across the same 12 design partners, findings with an attached fix draft were resolved 3.1× more often than findings with an auto-opened PR.",
      "- Trust improved. Reviewers no longer associated \"Dockier opened a PR\" with \"low-quality change in my repo.\" When they did open one, it was deliberate.",
      "- Cost dropped. We weren't generating fix code for findings nobody would ever look at. Drafts are generated lazily on first click.",
      "## The deeper lesson",
      "AI features want to be commitments because commitments are demo-able. But the unit of work in a developer's day is rarely a commitment — it's an option. Auto-complete is the canonical example: it suggests, you accept or ignore, the suggestion costs nothing if you skip it. AI fix PRs violated that contract.",
      "Our internal heuristic now: if a generated artefact would survive being deleted without your approval, it shouldn't be created proactively. PRs survive. Comments survive. Issues survive. Drafts don't — they sit attached to a finding and get cleaned up automatically.",
      "> We kept one auto-PR flow: when the finding is a known-deterministic upgrade (e.g. \"this CVE is fixed by bumping requests to 2.32.1\") and the change passes the repo's existing CI in a sandbox, we'll open the PR automatically. Those have a 94% merge rate. Everything else is a draft.",
    ],
  },
];

export function getPostBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}